frameworkVersion: "^3"
useDotenv: true
service: ${env:SVC_NAME}
provider:
  name: aws
  runtime: "nodejs18.x"
  timeout: 25
  deploymentMethod: "direct"
package:
  patterns:
    - "!**"
    - "handler.mjs"
    - "node_modules/**"
    - "src/**"
    - ".env"
functions:
  service:
    handler: "lambda.handler"
    events:
      - httpApi: "*"